// <auto-generated />
namespace VTCT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nonRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202012291935172_nonRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
